name: 🏗️ Build the core java jar
on:
  workflow_call:
  workflow_dispatch:
  #
  #I don't think we need this to run on any pushes. Re-evaluate after testing.
  # push:
  #   branches-ignore:
  #     - main

permissions:
  contents: write
  packages: write
  deployments: write

jobs:
  build:
    defaults:
      run:
        working-directory: repos/java
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4.2.2
      with:
        path: repos/java
        repository: 'pde-build-demo/java'
        fetch-depth: 0

    - run: |
        pwd
        ls -al
        echo $PATH
        ls -al /
        ls -al /usr/bin
        ls -al /bin

    - run: npm i conventional-changelog-conventionalcommits@7.0.2

    - name: Conventional Changelog Action
      id: changelog
      uses: TriPSs/conventional-changelog-action@v5.3.0
      with:
        config-file-path: ./.changelog.config.js
        skip-version-file: true
        skip-commit: true
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Maven
      uses: stCarolas/setup-maven@v4.4
      with:
        maven-version: 3.6.3

    - name: Cache maven files
      id: maven-cache
      uses: actions/cache@v4.2.0
      with:
        path: ~/.m2/repository
        key: maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: maven-

    - name: Set up JDK 17
      uses: actions/setup-java@v4.5.0
      with:
        cache: maven
        distribution: zulu
        java-version: 17

    - name: Deploy to GitHub maven repo
      run: mvn --no-transfer-progress -Djgitver.use-version=${{ steps.changelog.outputs.version }} -DuseGitHubPackages=true clean deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create a GitHub release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "target/*.jar,target/CHANGELOG.md"
        tag: ${{ steps.changelog.outputs.tag }}
        name: Release ${{ steps.changelog.outputs.version }}
        body: ${{ steps.changelog.outputs.clean_changelog }}
        token: ${{ secrets.GITHUB_TOKEN }}
